# Generated by Django 2.2 on 2019-11-01 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('energy_units', models.CharField(choices=[('J/mol', 'J/mol'), ('kJ/mol', 'kJ/mol'), ('cal/mol', 'cal/mol'), ('kcal/mol', 'kcal/mol'), ('cm^-1', 'cm^-1')], default='kcal/mol', max_length=100, verbose_name='Energy units')),
                ('heat_capacity_units', models.CharField(choices=[('J/(mol*K)', 'J/mol*K'), ('kJ/(mol*K)', 'kJ/mol*K'), ('cal/(mol*K)', 'cal/mol*K'), ('kcal/(mol*K)', 'kcal/mol*K')], default='cal/(mol*K)', max_length=100, verbose_name='Heat capacity units')),
                ('rate_coefficient_units', models.CharField(choices=[('m^3,mol,s', 'm^3, mol, s'), ('cm^3,mol,s', 'cm^3, mol, s'), ('m^3,molecule,s', 'm^3, molecule, s'), ('cm^3,molecule,s', 'cm^3, molecule, s')], default='cm^3,mol,s', max_length=100, verbose_name='Rate coefficient units')),
                ('temperature_units', models.CharField(choices=[('K', 'K')], default='K', max_length=100, verbose_name='Temperature units')),
                ('pressure_units', models.CharField(choices=[('Pa', 'Pa'), ('bar', 'bar'), ('atm', 'atm'), ('torr', 'torr')], default='bar', max_length=100, verbose_name='Pressure units')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
