# First, install a conda environment with RMG-Py.
# Then, update the environment using the constraints in this environment file.

name: rmg_website
channels:
  - conda-forge
dependencies:
  - django==4.2
  - python>=3.9
  - xlsxwriter
  - cantera==2.6.0*
