# First, install a conda environment with RMG-Py.
# Then, update the environment using the constraints in this environment file.

name: rmg_website
channels:
  - conda-forge
  - simonabuzzi
  - fhvermei
  - rmg
dependencies:
  - django==4.2
  - simonabuzzi::solprop_ml_mix
  - wandb # Required for solprop_ml_mix
  - python>=3.9
  - xlsxwriter
  - scipy>=1.9,<=1.10 # need 1.9.0 or greater for milp but < 1.11 because of gilbrat/gibrat deprecation for compat. with descriptastorus
  - cantera==2.6.0*
  - lxml # dependency for exporting to csv
