# First, install a conda environment with RMG-Py.
# Then, update the environment using the constraints in this environment file.

name: rmg_website
channels:
  - conda-forge
  - roelleenhouts
  - fhvermei
dependencies:
  - django==4.2
  - pip
  - pip:
      - git+https://github.com/bp-kelley/descriptastorus@2.5.0
  - roelleenhouts::solprop_ml
  - python>=3.9
  - xlsxwriter
  - fhvermei::chemprop_solvation
