# Generated by Django 2.2 on 2019-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmg', '0002_remove_fluxdiagram_java'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxdiagram',
            name='java',
            field=models.BooleanField(default=False, verbose_name='From RMG-Java'),
        ),
    ]
