# Generated by Django 2.2.5 on 2020-07-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmg', '0006_auto_20200219_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermolibrary',
            name='thermo_lib',
            field=models.CharField(blank=True, choices=[('BurcatNS', 'BurcatNS'), ('BurkeH2O2', 'BurkeH2O2'), ('C10H11', 'C10H11'), ('C3', 'C3'), ('CBS_QB3_1dHR', 'CBS_QB3_1dHR'), ('CH', 'CH'), ('CHN', 'CHN'), ('CHO', 'CHO'), ('CHON', 'CHON'), ('CN', 'CN'), ('Chernov', 'Chernov'), ('Chlorinated_Hydrocarbons', 'Chlorinated_Hydrocarbons'), ('CurranPentane', 'CurranPentane'), ('DFT_QCI_thermo', 'DFT_QCI_thermo'), ('FFCM1(-)', 'FFCM1(-)'), ('Fulvene_H', 'Fulvene_H'), ('GRI-Mech3.0', 'GRI-Mech3.0'), ('GRI-Mech3.0-N', 'GRI-Mech3.0-N'), ('JetSurF1.0', 'JetSurF1.0'), ('JetSurF2.0', 'JetSurF2.0'), ('Klippenstein_Glarborg2016', 'Klippenstein_Glarborg2016'), ('Lai_Hexylbenzene', 'Lai_Hexylbenzene'), ('NISTThermoLibrary', 'NISTThermoLibrary'), ('NOx2018', 'NOx2018'), ('Narayanaswamy', 'Narayanaswamy'), ('NitrogenCurran', 'NitrogenCurran'), ('SABIC_aromatics', 'SABIC_aromatics'), ('SulfurGlarborgBozzelli', 'SulfurGlarborgBozzelli'), ('SulfurGlarborgH2S', 'SulfurGlarborgH2S'), ('SulfurGlarborgMarshall', 'SulfurGlarborgMarshall'), ('SulfurGlarborgNS', 'SulfurGlarborgNS'), ('SulfurHaynes', 'SulfurHaynes'), ('SulfurLibrary', 'SulfurLibrary'), ('USC-Mech-ii', 'USC-Mech-ii'), ('bio_oil', 'bio_oil'), ('iodinated_Hydrocarbons', 'iodinated_Hydrocarbons'), ('naphthalene_H', 'naphthalene_H'), ('primaryNS', 'primaryNS'), ('primaryThermoLibrary', 'primaryThermoLibrary'), ('s3_5_7_ane', 's3_5_7_ane'), ('surfaceThermoNi', 'surfaceThermoNi'), ('surfaceThermoPt', 'surfaceThermoPt'), ('thermo_DFT_CCSDTF12_BAC', 'thermo_DFT_CCSDTF12_BAC'), ('vinylCPD_H', 'vinylCPD_H')], max_length=200),
        ),
    ]
