# Generated by Django 2.2.5 on 2020-02-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solventselection',
            name='solvent_temp',
            field=models.CharField(blank=True, choices=[('water', 'water: 280 K - 647.10 K'), ('benzene', 'benzene: 280 K - 562.02 K'), ('cyclohexane', 'cyclohexane: 280 K - 553.60 K'), ('octane', 'octane: 280 K - 569.32 K'), ('decane', 'decane: 280 K - 617.70 K'), ('dichloroethane', 'dichloroethane: 280 K - 561.60 K'), ('dodecane', 'dodecane: 280 K - 658.10 K'), ('ethanol', 'ethanol: 280 K - 514.71 K'), ('heptane', 'heptane: 280 K - 540.13 K'), ('hexane', 'hexane: 280 K - 540.13 K'), ('nonane', 'nonane: 280 K - 594.55 K'), ('pentane', 'pentane: 280 K - 469.70 K'), ('toluene', 'toluene: 280 K - 591.75 K'), ('undecane', 'undecane: 280 K - 638.80 K'), ('methanol', 'methanol: 280 K - 512.50 K')], max_length=200, verbose_name='Solvent'),
        ),
        migrations.AddField(
            model_name='solventselection',
            name='temp',
            field=models.FloatField(blank=True, default=298.0, verbose_name='Temperature in K (Optional)'),
        ),
        migrations.AlterField(
            model_name='solventselection',
            name='solvent',
            field=models.CharField(blank=True, choices=[('water', 'water'), ('1-octanol', '1-octanol'), ('benzene', 'benzene'), ('cyclohexane', 'cyclohexane'), ('dibutylether', 'dibutylether'), ('octane', 'octane'), ('butanol', 'butanol'), ('carbontet', 'carbontet'), ('chloroform', 'chloroform'), ('decane', 'decane'), ('dichloroethane', 'dichloroethane'), ('dimethylformamide', 'dimethylformamide'), ('dimethylsulfoxide', 'dimethylsulfoxide'), ('dodecane', 'dodecane'), ('ethanol', 'ethanol'), ('heptane', 'heptane'), ('hexadecane', 'hexadecane'), ('hexane', 'hexane'), ('isooctane', 'isooctane'), ('nonane', 'nonane'), ('pentane', 'pentane'), ('toluene', 'toluene'), ('undecane', 'undecane'), ('acetonitrile', 'acetonitrile'), ('ethylacetate', 'ethylacetate'), ('methanol', 'methanol'), ('methanol_50_water_50', 'methanol_50_water_50'), ('acetonitrile_40_water_60', 'acetonitrile_40_water_60'), ('acetonitrile_60_water_40', 'acetonitrile_60_water_40')], max_length=200, verbose_name='Solvent (Optional)'),
        ),
    ]
