# Generated by Django 2.2.5 on 2020-02-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200213_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solventselection',
            name='solvent_temp',
            field=models.CharField(blank=True, choices=[('water', 'water: 280 K - 647.10 K'), ('benzene', 'benzene: 280 K - 562.02 K'), ('cyclohexane', 'cyclohexane: 280 K - 553.60 K'), ('octane', 'octane: 280 K - 569.32 K'), ('decane', 'decane: 280 K - 617.70 K'), ('dichloroethane', 'dichloroethane: 280 K - 561.60 K'), ('dodecane', 'dodecane: 280 K - 658.10 K'), ('ethanol', 'ethanol: 280 K - 514.71 K'), ('heptane', 'heptane: 280 K - 540.13 K'), ('hexane', 'hexane: 280 K - 540.13 K'), ('nonane', 'nonane: 280 K - 594.55 K'), ('pentane', 'pentane: 280 K - 469.70 K'), ('toluene', 'toluene: 280 K - 591.75 K'), ('undecane', 'undecane: 280 K - 638.80 K')], max_length=200, verbose_name='Solvent'),
        ),
    ]
