# Generated by Django 2.2.5 on 2020-02-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200215_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solventselection',
            name='solvent_temp',
            field=models.CharField(blank=True, choices=[('water', 'water: 280 K - 647.09 K'), ('benzene', 'benzene: 280 K - 562.01 K'), ('cyclohexane', 'cyclohexane: 280 K - 553.59 K'), ('octane', 'octane: 280 K - 569.31 K'), ('decane', 'decane: 280 K - 617.69 K'), ('dichloroethane', 'dichloroethane: 280 K - 561.59 K'), ('dodecane', 'dodecane: 280 K - 658.09 K'), ('ethanol', 'ethanol: 280 K - 514.70 K'), ('heptane', 'heptane: 280 K - 540.12 K'), ('hexane', 'hexane: 280 K - 507.81 K'), ('nonane', 'nonane: 280 K - 594.54 K'), ('pentane', 'pentane: 280 K - 469.69 K'), ('toluene', 'toluene: 280 K - 591.74 K'), ('undecane', 'undecane: 280 K - 638.79 K')], max_length=200, verbose_name='Solvent'),
        ),
    ]
