# Generated by Django 2.2.5 on 2020-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200215_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solventselection',
            name='solvent',
            field=models.CharField(blank=True, choices=[('water', 'water'), ('1-octanol', '1-octanol'), ('benzene', 'benzene'), ('cyclohexane', 'cyclohexane'), ('dibutylether', 'dibutylether'), ('octane', 'octane'), ('butanol', 'butanol'), ('carbontet', 'carbontet'), ('chloroform', 'chloroform'), ('decane', 'decane'), ('dichloroethane', 'dichloroethane'), ('dimethylformamide', 'dimethylformamide'), ('dimethylsulfoxide', 'dimethylsulfoxide'), ('dodecane', 'dodecane'), ('ethanol', 'ethanol'), ('heptane', 'heptane'), ('hexadecane', 'hexadecane'), ('hexane', 'hexane'), ('isooctane', 'isooctane'), ('nonane', 'nonane'), ('pentane', 'pentane'), ('toluene', 'toluene'), ('undecane', 'undecane'), ('acetonitrile', 'acetonitrile'), ('ethylacetate', 'ethylacetate'), ('Acetone', 'Acetone'), ('carbondisulfide', 'carbondisulfide'), ('chlorobenzene', 'chlorobenzene'), ('decanol', 'decanol'), ('diethylether', 'diethylether'), ('heptanol', 'heptanol'), ('hexanol', 'hexanol'), ('isopropanol', 'isopropanol'), ('pentanol', 'pentanol'), ('propanol', 'propanol'), ('sec-butanol', 'sec-butanol'), ('tetrahydrofuran', 'tetrahydrofuran'), ('nitrobenzene', 'nitrobenzene'), ('diisopropylether', 'diisopropylether')], max_length=200, verbose_name='Solvent (Optional)'),
        ),
        migrations.AlterField(
            model_name='solventselection',
            name='solvent_temp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Solvent'),
        ),
    ]
