# Generated by Django 2.2 on 2019-11-01 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rmgweb.pdep.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.CharField(default=rmgweb.pdep.models._createId, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('input_file', models.FileField(upload_to=rmgweb.pdep.models.uploadTo, verbose_name='Input file')),
                ('input_text', models.TextField(blank=True, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
